import pyautogui as p
from selenium.webdriver import Chrome
from openpyxl import Workbook
import warnings
import pyperclip
import rpa as r
import pandas as pd
from openpyxl import load_workbook
import os
import pygetwindow as gw
import selenium
import pyperclip as pc
from selenium.webdriver import Chrome
from selenium.webdriver.common.keys import Keys

r.init(visual_automation=True, chrome_browser=False)

option = p.confirm('Selecione a entidade do relatório:', buttons=['IEL','FIESC','SENAI','SESI'])

if option != None:
    if option == 'IEL':
        os.startfile(r'\\sistemafiesc.org\NETLOGON\Atalhos\RemoteAPP\BENNER\Produção\CORPORATIVO_OFICIAL_NS06.rdp')

        p.sleep(6)

        # O robô vai esperar que o app do Benner seja aberto, ele vai verificar se existe os campos de usuário e senha para preencher e depois ele irá clicar no botão ok.

        if r.present('bennerAberto.png')==True:
            if r.present('usuarioBenner.png')==True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl','v')
                if r.present('senhaBenner.png')==True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
        else:
            r.wait(r.present('bennerAberto.png'))
            if r.present('usuarioBenner.png')==True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl','v')
                if r.present('senhaBenner.png')==True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')

        if r.present('okBotao.png')==True:
            r.click('okBotao.png')
        else:
            r.wait(r.present('okBotao.png'))
            r.click('okBotao.png')
        p.sleep(15)

        janela = gw.getActiveWindow()
        janela.maximize()

        # Após isso, ele vai verificar qual entidade está sendo visualizada.
        if r.present('abaIEL.png')==True:
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        else:
            r.click('casaEntidade.png')
            r.click('diminuirLista.png')
            r.dclick('selecionarIEL.png')
            r.dclick('botaoTF.png')
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        p.sleep(2)
        r.dclick('grupoRelatorios.png')
        r.dclick('inventariosIEL.png')
        r.dclick('relatorios.png')
        r.click('bensPorLocalizacao.png')
        r.click('imprimirRelatorio.png')
        r.click('selecionarAT_ITENS.png')
        r.click('monitor.png')
        r.click('filtroIEL.png')
        r.click('filtrar.png')
        r.wait(r.present('salvarRelatorio.png'))
        p.sleep(10)
        r.click('salvarRelatorio.png')
        r.click('esteComputador.png')
        r.dclick('unidadeC.png')
        r.dclick('pastaUsuarios.png')
        r.dclick('pastaLucasGomes.png')
        r.dclick('areaDeTrabalho.png')
        p.sleep(1)
        r.wait(r.present('nomeDoArquivo.png'))
        r.click('nomeDoArquivo.png')
        p.sleep(1)
        pyperclip.copy('ConferenciasIEL')
        p.sleep(1)
        p.hotkey('ctrl', 'v')
        p.sleep(1)
        p.hotkey('enter')
        p.sleep(1)
        nomearquivo = p.prompt('Qual nome você dará ao arquivo?')
        pyperclip.copy(str(nomearquivo))
        r.click('nomeDoArquivo.png')
        p.hotkey('ctrl', 'v')
        r.click('tipoDeArquivo.png')
        r.click('arquivoTipoExcel.png')
        r.click('salvarXLSX.png')
        p.sleep(10)
        r.wait(r.present('bennerInativo.png'))
        r.rclick('bennerInativo.png')
        p.sleep(2)
        r.click('fecharJanela.png')
        p.sleep(5)

    elif option == 'FIESC':
        os.startfile(r'\\sistemafiesc.org\NETLOGON\Atalhos\RemoteAPP\BENNER\Produção\CORPORATIVO_OFICIAL_NS06.rdp')

        p.sleep(6)

        # O robô vai esperar que o app do Benner seja aberto, ele vai verificar se existe os campos de usuário e senha para preencher e depois ele irá clicar no botão ok.

        if r.present('bennerAberto.png') == True:
            if r.present('usuarioBenner.png') == True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
        else:
            r.wait(r.present('bennerAberto.png'))
            if r.present('usuarioBenner.png') == True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')

        if r.present('okBotao.png') == True:
            r.click('okBotao.png')
        else:
            r.wait(r.present('okBotao.png'))
            r.click('okBotao.png')
        p.sleep(15)

        janela = gw.getActiveWindow()
        janela.maximize()

        # Após isso, ele vai verificar qual entidade está sendo visualizada.
        if r.present('abaFIESC.png') == True:
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        else:
            r.click('casaEntidade.png')
            r.click('diminuirLista.png')
            r.dclick('selecionarFIESC.png')
            r.dclick('botaoTF.png')
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        p.sleep(2)
        r.dclick('grupoRelatorios.png')
        r.dclick('inventariosFIESC.png')
        r.dclick('relatorios.png')
        r.click('bensPorLocalizacao.png')
        r.click('imprimirRelatorio.png')
        r.click('selecionarAT_ITENS.png')
        r.click('monitor.png')
        r.click('filtrar.png')
        r.wait(r.present('salvarRelatorio.png'))
        p.sleep(10)
        r.click('salvarRelatorio.png')
        r.click('esteComputador.png')
        r.dclick('unidadeC.png')
        r.dclick('pastaUsuarios.png')
        r.dclick('pastaLucasGomes.png')
        r.dclick('areaDeTrabalho.png')
        p.sleep(1)
        r.wait(r.present('nomeDoArquivo.png'))
        r.click('nomeDoArquivo.png')
        p.sleep(1)
        pyperclip.copy('ConferenciasFIESC')
        p.sleep(1)
        p.hotkey('ctrl', 'v')
        p.sleep(1)
        p.hotkey('enter')
        p.sleep(1)
        nomearquivo = p.prompt('Qual nome você dará ao arquivo?')
        pyperclip.copy(str(nomearquivo))
        r.click('nomeDoArquivo.png')
        p.hotkey('ctrl', 'v')
        r.click('tipoDeArquivo.png')
        r.click('arquivoTipoExcel.png')
        r.click('salvarXLSX.png')
        p.sleep(10)
        r.wait(r.present('bennerInativo.png'))
        r.rclick('bennerInativo.png')
        p.sleep(2)
        r.click('fecharJanela.png')
        p.sleep(5)

    elif option == 'SENAI':
        os.startfile(r'\\sistemafiesc.org\NETLOGON\Atalhos\RemoteAPP\BENNER\Produção\CORPORATIVO_OFICIAL_NS06.rdp')

        p.sleep(6)

        # O robô vai esperar que o app do Benner seja aberto, ele vai verificar se existe os campos de usuário e senha para preencher e depois ele irá clicar no botão ok.

        if r.present('bennerAberto.png') == True:
            if r.present('usuarioBenner.png') == True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
        else:
            r.wait(r.present('bennerAberto.png'))
            if r.present('usuarioBenner.png') == True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')

        if r.present('okBotao.png') == True:
            r.click('okBotao.png')
        else:
            r.wait(r.present('okBotao.png'))
            r.click('okBotao.png')
        p.sleep(15)

        janela = gw.getActiveWindow()
        janela.maximize()

        # Após isso, ele vai verificar qual entidade está sendo visualizada.
        if r.present('aba.png') == True:
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        else:
            r.click('casaEntidade.png')
            r.click('diminuirLista.png')
            r.dclick('selecionarSENAI.png')
            r.dclick('botaoTF.png')
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        p.sleep(2)
        r.dclick('grupoRelatorios.png')
        r.dclick('inventariosSENAI.png')
        r.dclick('relatorios.png')
        r.click('bensPorLocalizacao.png')
        r.click('imprimirRelatorio.png')
        r.click('selecionarAT_ITENS.png')
        r.click('monitor.png')
        r.click('filtroSENAI.png')
        r.click('filtrar.png')
        r.wait(r.present('salvarRelatorio.png'))
        p.sleep(10)
        r.click('salvarRelatorio.png')
        r.click('esteComputador.png')
        r.dclick('unidadeC.png')
        r.dclick('pastaUsuarios.png')
        r.dclick('pastaLucasGomes.png')
        r.dclick('areaDeTrabalho.png')
        p.sleep(1)
        r.wait(r.present('nomeDoArquivo.png'))
        r.click('nomeDoArquivo.png')
        p.sleep(1)
        pyperclip.copy('ConferenciasSENAI')
        p.sleep(1)
        p.hotkey('ctrl', 'v')
        p.sleep(1)
        p.hotkey('enter')
        p.sleep(1)
        nomearquivo = p.prompt('Qual nome você dará ao arquivo?')
        pyperclip.copy(str(nomearquivo))
        r.click('nomeDoArquivo.png')
        p.hotkey('ctrl', 'v')
        r.click('tipoDeArquivo.png')
        r.click('arquivoTipoExcel.png')
        r.click('salvarXLSX.png')
        p.sleep(10)
        r.wait(r.present('bennerInativo.png'))
        r.rclick('bennerInativo.png')
        p.sleep(2)
        r.click('fecharJanela.png')
        p.sleep(5)

    elif option == 'SESI':
        os.startfile(r'\\sistemafiesc.org\NETLOGON\Atalhos\RemoteAPP\BENNER\Produção\CORPORATIVO_OFICIAL_NS06.rdp')

        p.sleep(6)

        # O robô vai esperar que o app do Benner seja aberto, ele vai verificar se existe os campos de usuário e senha para preencher e depois ele irá clicar no botão ok.

        if r.present('bennerAberto.png') == True:
            if r.present('usuarioBenner.png') == True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
        else:
            r.wait(r.present('bennerAberto.png'))
            if r.present('usuarioBenner.png') == True:
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
            else:
                r.wait(r.present('usuarioBenner.png'))
                r.click('usuarioBenner.png')
                pyperclip.copy('lucas.gomes')
                p.sleep(1)
                p.hotkey('ctrl', 'v')
                if r.present('senhaBenner.png') == True:
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')
                else:
                    r.wait(r.present('senhaBenner.png'))
                    r.click('senhaBenner.png')
                    pyperclip.copy('Lucasgg17*')
                    p.sleep(1)
                    p.hotkey('ctrl', 'v')

        if r.present('okBotao.png') == True:
            r.click('okBotao.png')
        else:
            r.wait(r.present('okBotao.png'))
            r.click('okBotao.png')
        p.sleep(15)

        janela = gw.getActiveWindow()
        janela.maximize()

        # Após isso, ele vai verificar qual entidade está sendo visualizada.
        if r.present('aba.png') == True:
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        else:
            r.click('casaEntidade.png')
            r.click('diminuirLista.png')
            r.dclick('selecionarSESI.png')
            r.dclick('botaoTF.png')
            if r.present('ativoDesselecionado.png') == True:
                r.click('ativoDesselecionado.png')
        p.sleep(2)
        r.dclick('grupoRelatorios.png')
        r.dclick('inventariosSESI.png')
        r.dclick('relatorios.png')
        r.click('bensPorLocalizacao.png')
        r.click('imprimirRelatorio.png')
        r.click('selecionarAT_ITENS.png')
        r.click('monitor.png')
        r.click('filtroSESI.png')
        r.click('filtrar.png')
        r.wait(r.present('salvarRelatorio.png'))
        p.sleep(10)
        r.click('salvarRelatorio.png')
        r.click('esteComputador.png')
        r.dclick('unidadeC.png')
        r.dclick('pastaUsuarios.png')
        r.dclick('pastaLucasGomes.png')
        r.dclick('areaDeTrabalho.png')
        p.sleep(1)
        r.wait(r.present('nomeDoArquivo.png'))
        r.click('nomeDoArquivo.png')
        p.sleep(1)
        pyperclip.copy('ConferenciasSESI')
        p.sleep(1)
        p.hotkey('ctrl', 'v')
        p.sleep(1)
        p.hotkey('enter')
        p.sleep(1)
        nomearquivo = p.prompt('Qual nome você dará ao arquivo?')
        pyperclip.copy(str(nomearquivo))
        r.click('nomeDoArquivo.png')
        p.sleep(1)
        p.hotkey('ctrl', 'v')
        p.sleep(1)
        r.click('tipoDeArquivo.png')
        p.sleep(1)
        r.click('arquivoTipoExcel.png')
        p.sleep(1)
        r.click('salvarXLSX.png')
        p.sleep(10)
        r.wait(r.present('bennerInativo.png'))
        r.rclick('bennerInativo.png')
        p.sleep(2)
        r.click('fecharJanela.png')
        p.sleep(5)
    pasta = ''
    if option == 'IEL':
        pasta = 'ConferenciasIEL'
    elif option == 'FIESC':
        pasta = 'ConferenciasFIESC'
    elif option == 'SESI':
        pasta = 'ConferenciasSESI'
    elif option == 'SENAI':
        pasta = 'ConferenciasSENAI'
    os.startfile(r'C:\Users\lucas.gomes\Desktop\{}\{}'.format(str(pasta), str(nomearquivo) + '.xlsx'))
    r.wait(r.present('excelAberto2.png'))
    janela = gw.getActiveWindow()
    janela.maximize()
    p.sleep(6)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('s')
    p.sleep(1.5)
    p.hotkey('p', 'n')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(2)
    r.wait(r.present('barraDePesquisa.png'))
    r.click('barraDePesquisa.png')
    p.sleep(1)
    pyperclip.copy(r'C:\Users\lucas.gomes\Desktop\{}'.format(str(pasta)))
    p.hotkey('ctrl', 'v')
    p.sleep(1)
    p.hotkey('enter')
    p.sleep(1)
    r.wait(r.present('pesquisarConferencia.png'))
    r.click('pesquisarConferencia.png')
    p.sleep(1)
    pyperclip.copy(str(nomearquivo))
    p.hotkey('ctrl', 'v')
    p.sleep(1)
    p.hotkey('enter')
    p.sleep(1)
    p.hotkey('down')
    p.sleep(1)
    p.hotkey('up')
    p.sleep(1)
    p.hotkey('enter')
    r.wait(r.present('selecionarDados.png'))
    p.sleep(1.5)
    r.dclick('selecionarRelatorio.png')
    p.sleep(1.5)
    r.wait(r.present('sorriso.png'))
    p.sleep(4)
    r.wait(r.present('coluna1Presente.png'))
    p.hotkey('p', 'u')
    p.sleep(1.5)
    p.hotkey('e')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('t')
    p.sleep(1.5)
    p.hotkey('f', 'i')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('t')
    r.wait(r.present('transformarAberto.png'))
    p.hotkey('f', 'i')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('l')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('h')
    p.sleep(1.5)
    p.hotkey('w')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(4)
    p.hotkey('2')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(2)
    p.hotkey('tab')
    p.sleep(1.5)
    p.hotkey('tab')
    p.sleep(1.5)
    p.hotkey('tab')
    p.sleep(1.5)
    p.hotkey('tab')
    p.sleep(1.5)
    p.hotkey('tab')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    r.wait(r.present('filtroColuna.png'))
    r.click('filtroColuna.png')
    p.sleep(1.5)
    r.wait(r.present('pesquisarFiltro.png'))
    r.click('pesquisarFiltro.png')
    p.sleep(1.5)
    nulo = pyperclip.copy('nulo')
    p.hotkey('ctrl', 'v')
    r.wait(r.present('clicarNulo.png'))
    r.click('clicarNulo.png')
    p.sleep(1.5)
    r.click('apagar.png')
    p.sleep(1.5)
    cod = pyperclip.copy('cod')
    p.hotkey('ctrl', 'v')
    r.wait(r.present('clicarCod.png'))
    r.click('clicarCod.png')
    p.sleep(1.5)
    r.click('apagar.png')
    p.sleep(1.5)
    p.hotkey('enter')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('f')
    p.sleep(1.5)
    p.hotkey('enter')
    r.wait(r.present('excelAberto2.png'))
    p.sleep(4)
    coluna1 = pyperclip.copy('N° Plaqueta')
    p.hotkey('ctrl', 'v')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    coluna2 = pyperclip.copy('Localização')
    p.hotkey('ctrl', 'v')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    coluna3 = pyperclip.copy('Descrição')
    p.hotkey('ctrl', 'v')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    coluna4 = pyperclip.copy('Regional')
    p.hotkey('ctrl', 'v')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    coluna5 = pyperclip.copy('Data de Aquisição')
    p.hotkey('ctrl', 'v')
    p.sleep(1.5)
    p.hotkey('right')
    p.sleep(1.5)
    coluna6 = pyperclip.copy('Responsável')
    p.hotkey('ctrl', 'v')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    p.hotkey('left')
    p.sleep(1.5)
    r.rclick('colunaB.png')
    p.sleep(1.5)
    r.wait(r.present('inserir.png'))
    r.click('inserir.png')
    p.sleep(1.5)
    p.hotkey('down')
    p.sleep(1.5)
    p.hotkey('up')
    p.sleep(1.5)
    conformidade = pyperclip.copy('Conformidade do Termo')
    p.hotkey('ctrl', 'v')
    p.sleep(1.5)
    r.wait(r.present('planilhaRelatorio.png'))
    r.rclick('planilhaRelatorio.png')
    p.sleep(1.5)
    r.click('excluirPlanilha.png')
    p.sleep(1.5)
    r.click('excluirContinuar.png')
    p.sleep(1.5)
    p.hotkey('alt')
    p.sleep(1.5)
    p.hotkey('a')
    p.sleep(1.5)
    p.hotkey('s')
    r.close()

if option == None:
    print('Processo Terminado')
    r.close()


